export const Type = {
    SET_USER: 'SET_USER',
    SET_BASKET: 'SET_BASKET',
    ADD_TO_BASKET: 'ADD_TO_BASKET',
    INCREMENT_ITEM: 'INCREMENT_ITEM',
    DECREMENT_ITEM: 'DECREMENT_ITEM',
    CLEAR_BASKET: 'CLEAR_BASKET'
  };